Make it possible to use the debug versions of std::map and std::multimap with clang, by removing two unneeded using declarations.  Otherwise, you would get errors similar to:
/usr/include/c++/4.2/debug/map.h:77:20: error: dependent using declaration resolved to type without 'typename'
      using _Base::value_compare;
                   ^

N.B.: Take care when you actually use the debug versions of any
libstdc++ header.  They are more likely to contain problems, because
they are exercised far less often, and since the standard library
complexity guarantees don't always apply anymore, compile times can
drastically increase.

MFC after:	2 weeks


git-svn-id: svn://svn.freebsd.org/base/head@228328 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f